# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=${PORT:8080}


# ===============================
# SQL SERVER DATABASE CONNECTION
# ===============================

#spring.datasource.url=jdbc:sqlserver://DESKTOP-BAJSGSI\\SQLEXPRESS;databaseName=balaji_store;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=123456
#
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect



# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================



# ===============================
# LOGGING (OPTIONAL BUT USEFUL)
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE